### ISSUE TITLE
Setting the maxThreads param

### ISSUE THREAD

**Issue by iminkin** [glennhickey/progressiveCactus#113]
Hi,

Theoretically, does it make sense to set the maxThreads to parameter to the number smaller than the number of the cores available? Some programs run slower with too much parallelism, is it true for cactus?

**Comment by joelarmstrong** [comment]
Hi Ilya,

Theoretically, cactus might use a tiny bit of CPU in its 'bookkeeping' processes at the same time that the processes it's supervising are doing the real work. But that usage should be very minimal. You could set it a bit lower than the number of CPUs you have if you want to leave some spare room, but it almost certainly would run a bit slower, not faster.

**Comment by iminkin** [comment]
Thanks.
