### ISSUE TITLE
hal2assemblyHub.py failing to find Bio when run from progressiveCactus with "import source"

### ISSUE THREAD

**Issue by benedictpaten** [glennhickey/progressiveCactus#21]
Having run 
"source environment" I get an import error for Bio when running hal2assemblyhub.py, i.e.:

benedict@kolossus progressiveCactus]$ python submodules/hal/bin/hal2assemblyHub.py --help
## Usage: hal2assemblyHub.py <halFile> <outputDirectory> [options]

[benedict@kolossus progressiveCactus]$ source environment 
(python)[benedict@kolossus progressiveCactus]$ python submodules/hal/bin/hal2assemblyHub.py --help
Traceback (most recent call last):
  File "submodules/hal/bin/hal2assemblyHub.py", line 28, in <module>
    from hal.assemblyHub.prepareHubFiles import *
  File "/hive/users/benedict/progressiveCactus/submodules/hal/assemblyHub/prepareHubFiles.py", line 16, in <module>
    from Bio import Phylo
ImportError: No module named Bio
(python)[benedict@kolossus progressiveCactus]$

**Comment by ammeyer** [comment]
Hi all - just started using progressiveCactus and this is currently an issue for me - same traceback call:

(python)abrialmeyer~/Desktop/progressiveCactus/work :hal2assemblyHub.py lcb.hal outdir
Traceback (most recent call last):
  File "/Users/abrialmeyer/Desktop/progressiveCactus/submodules/hal/bin/hal2assemblyHub.py", line 28, in <module>
    from hal.assemblyHub.prepareHubFiles import *
  File "/Users/abrialmeyer/Desktop/progressiveCactus/submodules/hal/assemblyHub/prepareHubFiles.py", line 16, in <module>
    from Bio import Phylo
ImportError: No module named Bio

can i do anything to fix this?

**Comment by ammeyer** [comment]
I resolved this issue by bringing to Bio subfolder of biopython in the submodules folder up a level - into the submodules folder. 
Additionally, for hal2assemblyHub to run the jobTree folder has to be deleted if it was created in the progressiveCactus run

**Comment by joelarmstrong** [comment]
Sorry that we missed your issue comment before. Glad you ended up resolving it.

We plan to release a totally revamped Cactus "soon-ish" that will take care of a lot of these installation issues--it can definitely be very hard to get it going properly.

**Comment by ammeyer** [comment]
Hi Joel

Is there a more direct line of communication I could reach you at? My lab
group at the American Museum of Natural History is really interested in
further use of progressiveCactus.
My email is ameyer@amnh.org

Thank you!
Abby Meyer

**Comment by joelarmstrong** [comment]
I'm happy to communicate over email, it's a bit easier for me than github issues. You found my email, but for anyone who comes across this later, my email is jcarmstr@ucsc.edu.

**Comment by malcook** [comment]
Hi - just saw @ammeyer's workaround after reporting #83 suggesting alternate code fix...
