### ISSUE TITLE
error when "make"

### ISSUE THREAD

**Issue by yjx1217** [glennhickey/progressiveCactus#27]
Hello, I encountered the following error when trying to compile progressiveCactus on my working cluster. Could you help me to figure out the problem? Thx! The error message is as follow:

....
ktutiltest.o: In function `memusage()':
ktutiltest.cc:(.text._Z8memusagev[memusage()]+0x32): undefined reference to `kyotocabinet::getsysinfo(std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*)'
ktutiltest.o: In function `main':
ktutiltest.cc:(.text.startup+0x2c): undefined reference to `kyotocabinet::getenv(char const*)'
ktutiltest.cc:(.text.startup+0x29a): undefined reference to `kyotocabinet::setstdiobin()'
ktutiltest.cc:(.text.startup+0x47c): undefined reference to `kyotocabinet::getpid()'
ktutiltest.cc:(.text.startup+0xbaf): undefined reference to `kyotocabinet::Thread::Thread()'
ktutiltest.cc:(.text.startup+0xc33): undefined reference to `kyotocabinet::Thread::Thread()'
ktutiltest.cc:(.text.startup+0xc8f): undefined reference to `kyotocabinet::Thread::Thread()'
ktutiltest.cc:(.text.startup+0xceb): undefined reference to `kyotocabinet::Thread::Thread()'
ktutiltest.cc:(.text.startup+0xd54): undefined reference to `kyotocabinet::Thread::Thread()'
ktutiltest.o:ktutiltest.cc:(.text.startup+0xdb5): more undefined references to `kyotocabinet::Thread::Thread()' follow
ktutiltest.o: In function `main':
ktutiltest.cc:(.text.startup+0xeee): undefined reference to `kyotocabinet::time()'
ktutiltest.cc:(.text.startup+0xf4c): undefined reference to `kyotocabinet::Thread::start()'
ktutiltest.cc:(.text.startup+0xfc4): undefined reference to `kyotocabinet::Thread::start()'
ktutiltest.cc:(.text.startup+0x100c): undefined reference to `kyotocabinet::Thread::start()'
ktutiltest.cc:(.text.startup+0x1056): undefined reference to `kyotocabinet::Thread::start()'
ktutiltest.cc:(.text.startup+0x10ac): undefined reference to `kyotocabinet::Thread::start()'
ktutiltest.o:ktutiltest.cc:(.text.startup+0x10f6): more undefined references to `kyotocabinet::Thread::start()' follow
ktutiltest.o: In function `main':
ktutiltest.cc:(.text.startup+0x11bc): undefined reference to `kyotocabinet::Thread::join()'
ktutiltest.cc:(.text.startup+0x1204): undefined reference to `kyotocabinet::Thread::join()'
ktutiltest.cc:(.text.startup+0x1229): undefined reference to `kyotocabinet::Thread::join()'
ktutiltest.cc:(.text.startup+0x124f): undefined reference to `kyotocabinet::Thread::join()'
ktutiltest.cc:(.text.startup+0x1284): undefined reference to `kyotocabinet::Thread::join()'
ktutiltest.o:ktutiltest.cc:(.text.startup+0x12ae): more undefined references to `kyotocabinet::Thread::join()' follow
ktutiltest.o: In function `main':
ktutiltest.cc:(.text.startup+0x1335): undefined reference to `kyotocabinet::time()'
ktutiltest.cc:(.text.startup+0x1695): undefined reference to `kyotocabinet::time()'
ktutiltest.o: In function `kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)':
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x6b): undefined reference to `kyotocabinet::File::read_directory(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x8c): undefined reference to `kyotocabinet::File::EXTCHR'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0xd7): undefined reference to `kyotocabinet::File::PATHCHR'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x17f): undefined reference to `kyotocabinet::File::open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, long)'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x194): undefined reference to `kyotocabinet::SpinRWLock::lock_reader()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x222): undefined reference to `kyotocabinet::File::refresh()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x22e): undefined reference to `kyotocabinet::File::size() const'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x24a): undefined reference to `kyotocabinet::SpinRWLock::unlock()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x252): undefined reference to `kyotocabinet::File::close()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x289): undefined reference to `kyotocabinet::SpinRWLock::lock_reader()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x290): undefined reference to `kyotocabinet::File::EXTCHR'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x297): undefined reference to `kyotocabinet::File::PATHCHR'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x2e6): undefined reference to `kyotocabinet::File::open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, long)'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x31b): undefined reference to `kyotocabinet::SpinRWLock::unlock()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x330): undefined reference to `kyotocabinet::SpinRWLock::lock_reader()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x358): undefined reference to `kyotocabinet::SpinRWLock::unlock()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x39a): undefined reference to `kyotocabinet::File::close()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x3a7): undefined reference to `kyotocabinet::SpinRWLock::unlock()'
ktutiltest.cc:(.text._ZN11kyototycoon12UpdateLogger6Reader4openEPS0_m[kyototycoon::UpdateLogger::Reader::open(kyototycoon::UpdateLogger*, unsigned long)]+0x520): undefined reference to `kyotocabinet::File::read(long, void*, unsigned long)'
ktutiltest.o:(.data.rel.ro._ZTIN11kyototycoon12UpdateLogger11AutoFlusherE[typeinfo for kyototycoon::UpdateLogger::AutoFlusher]+0x10): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x10): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x30): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x50): undefined reference to `typeinfo for kyotocabinet::Thread'
ktutiltest.o:(.data.rel.ro+0x70): undefined reference to `typeinfo for kyotocabinet::Thread'
./libkyototycoon.so: undefined reference to `kyotocabinet::File::error() const'
./libkyototycoon.so: undefined reference to `kyotocabinet::DB::Visitor::NOP'
collect2: ld returned 1 exit status
make[2]: *** [ktutiltest] Error 1
make[2]: Leaving directory `/global/u2/y/yjx/Programs/progressiveCactus/submodules/kyototycoon'
make[1]: *** [kyototycoonRule] Error 2
make[1]: Leaving directory `/global/u2/y/yjx/Programs/progressiveCactus/submodules'
make: *** [all] Error 2

**Comment by fenderglass** [comment]
Confirm this bug with similar error on an old cluster (with new GCC environment though). Unforunately, none of the tips below has helped.

**Comment by fenderglass** [comment]
Finally, I found a solution that works for me. 
Adding "-lkyotocabinet" to the end of 2115 line of "submodules/kyototycoon/configure" does the trick.

**Comment by fenderglass** [comment]
It seems that I have found a solution that works for me.
Changing 2115 line in "submodules/kyototycoon/configure" from

    MYLDFLAGS="-L. -L\$(LIBDIR)"

to

    MYLDFLAGS="-L. -L\$(LIBDIR) -lkyotocabinet"

does the trick.
