### ISSUE TITLE
Compile error in hal2cactus

### ISSUE THREAD

**Issue by fenderglass** [glennhickey/progressiveCactus#40]
The latest progressiveCactus package won't build with the following log:

    cd cactus2hal && make
    make[2]: Entering directory `/home/kolmogorov/tools/progressiveCactus/submodules/cactus2hal'
    h5c++ -prefix=/home/kolmogorov/tools/progressiveCactus/submodules/hdf5 -O3 -g -Wall -funroll-loops -DNDEBUG  -I .//../sonLib/lib -I .//../cactus/lib -I .//../hal/lib -I /home/kolmogorov/tools/progressiveCactus/submodules/tokyocabinet/include -DHAVE_TOKYO_CABINET=1 -I/home/kolmogorov/tools/progressiveCactus/submodules/kyotocabinet/include -I/home/kolmogorov/tools/progressiveCactus/submodules/kyototycoon/include -DHAVE_KYOTO_TYCOON=1 -I/home/kolmogorov/tools/progressiveCactus/submodules/zlib/include  -D__STDC_LIMIT_MACROS -Wno-deprecated -I inc -I src -c src/*.cpp
    src/fastaReader.cpp:63:6: error: prototype for ‘void FastaReader::skipToSequence(const string&)’ does not match any in class ‘FastaReader’
     void FastaReader::skipToSequence(const string& sequenceName)
          ^
    In file included from src/fastaReader.cpp:11:0:
    inc/fastaReader.h:37:19: error: candidate is: std::streampos FastaReader::skipToSequence(const string&)
        std::streampos skipToSequence(const std::string& sequenceName);
                   ^
    make[2]: *** [lib//cactus2halLib.a] Error 1
    make[2]: Leaving directory `/home/kolmogorov/tools/progressiveCactus/submodules/cactus2hal'
    make[1]: *** [ucsc.cactus2hal] Error 2
    make[1]: Leaving directory `/home/kolmogorov/tools/progressiveCactus/submodules'
    make: *** [all] Error 2

If I replace line 37 in "fastaReader.h" from:

    std::streampos skipToSequence(const std::string& sequenceName);

to

    void skipToSequence(const std::string& sequenceName);

everything builds and runs fine.

**Comment by joelarmstrong** [comment]
Oops, this was a stupid merge error on my part. Thanks for catching it. It should be fixed now.
