### ISSUE TITLE
Alignment scores

### ISSUE THREAD

**Issue by lydiasteiner** [glennhickey/progressiveCactus#79]
Hi,

does cactus generate alignment scores for each alignment block? And if so, how can I extract when generating a MAF file out of the HAL output?

**Comment by joelarmstrong** [comment]
Hi Lydia,

We don't currently generate alignment scores, sorry. We've gotten similar requests from a few people, so we'll consider adding that in a future release.

**Comment by lydiasteiner** [comment]
Thanks for the quick answer. Alignment scores or a tool to score the alignment blocks afterwards would be great.
