### ISSUE TITLE
Allow progressive cactus to use UGE

### ISSUE THREAD

**Issue by ndukler** [glennhickey/progressiveCactus#82]
The cluster I use has UGE (Univa Grid Engine) on it, not SGE.
The jobs are being submitted using options that are not valid on my system:
(1) -l num_proc=1.0. If this is the number of threads per job then it should be “-pe threads” instead of “-l num_proc”.

(2) “-l virtual_free” is equivalent to “-l m_mem_free”.

**Comment by ndukler** [comment]
Figured it out. Made alterations to gridengine.py in the jobTree module.

**Comment by joelarmstrong** [comment]
Nice. I will make a note in the [toil repository](https://github.com/BD2KGenomics/toil) so that we can support UGE as well as SGE. (toil is the new version of jobTree, and the next version of Cactus will use toil).

**Comment by ndukler** [comment]
It might be useful to create a template for people to customize how the flags are constructed since I understand some of them vary from system to system, even within a single type of queue management software. Thanks for making a note!
