### ISSUE TITLE
job hanging 

### ISSUE THREAD

**Issue by aihardin** [glennhickey/progressiveCactus#85]
Hi! I'm trying to align three rodents and after 4 days of processing, the job seems to have hung. There is no cpu or disk activity and all the processes have wait, poll_s, or ep_pol status. The last line in the log is Breaking bar job into 3 separate jobs. Is there something I can do?

**Comment by joelarmstrong** [comment]
Hmm, that's not good. Sorry that you're having trouble. Are you running on a cluster, or just a single machine? Are there any `cactus_bar` or `ktserver` processes running, or are there only python processes left?

**Comment by aihardin** [comment]
Found the problem, filled up the disk. There were some ktserver processes running but nothing happened after I cleaned up more space so I killed the job. I was running this on a 256gb SSD temp drive and I guess that wasn't enough. My inputs are mouse/rat/new rodent of comparable genome size. How much temp space should I expect this to use?

**Comment by joelarmstrong** [comment]
Ah, that's a bummer. Is the work dir on the temp drive as well as /tmp? We will use some space in both (though likely much less than 50GB or so at a time in /tmp). The work dir could potentially get pretty large. I don't know how much it would take off the top of my head, but 256GB could be cutting it a little close.
